name: Lint golang code
on:
  pull_request:
    branches-ignore:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: run linter
        uses: reviewdog/action-golangci-lint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          golangci_lint_flags: "-c .golangci.yml"
